package pw.tests.addressbook;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CreateNewGroupTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createnewgroup() {
    // Test name: Create new group
    // Step # | name | target | value
    // 1 | open | /index.php | 
    driver.get("http://ab.localhost/index.php");
    // 2 | setWindowSize | 1680x1025 | 
    driver.manage().window().setSize(new Dimension(1680, 1025));
    // 3 | type | name=user | admin
    driver.findElement(By.name("user")).sendKeys("admin");
    // 4 | type | name=pass | secret
    driver.findElement(By.name("pass")).sendKeys("secret");
    // 5 | click | css=input:nth-child(7) | 
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    // 6 | click | linkText=groups | 
    driver.findElement(By.linkText("groups")).click();
    // 7 | click | name=new | 
    driver.findElement(By.name("new")).click();
    // 8 | click | name=group_name | 
    driver.findElement(By.name("group_name")).click();
    // 9 | type | name=group_name | test1
    driver.findElement(By.name("group_name")).sendKeys("test1");
    // 10 | click | name=group_header | 
    driver.findElement(By.name("group_header")).click();
    // 11 | type | name=group_header | test2
    driver.findElement(By.name("group_header")).sendKeys("test2");
    // 12 | click | name=group_footer | 
    driver.findElement(By.name("group_footer")).click();
    // 13 | type | name=group_footer | test3
    driver.findElement(By.name("group_footer")).sendKeys("test3");
    // 14 | click | name=submit | 
    driver.findElement(By.name("submit")).click();
    // 15 | click | linkText=group page | 
    driver.findElement(By.linkText("group page")).click();
  }
}
